### PR TITLE
Support for building explicit water/ion boxes using tleap

### LINKED ISSUE #46: Allow explicit water boxes in system builder
For convenience, it would helpful to be able to make extended peptides in explicit solvent using the `SystemBuilder` alone, rather than doing some tleap stuff outside of MELD and loading the top/mdcrd. `SystemBuilder` should be modified to include new optional parameters for solvent type and box size. https://github.com/maccallumlab/meld/blob/master/meld/system/builder.py#L32

Essentially, new lines should be added to leap_cmds before `_generate_leap_footer`, something along the lines of:

```
leap_cmds.extend(["source leaprc.water.tip3p","solvateBox mol_0 TIP3PBOX 6"])
```

where the type of solvent and distance to box edge should be adjustable parameters. Of course, there are other commands like `addIons` that could also be supported as well.

Any preference on if we should make this general, to accept any leap_cmds as argument to SystemBuilder, or just specific keywords to make explicit waterboxes and ions?

By the way, does anyone know if truncated octahedron box sizes (via `solvateOct`) are inherently supported in MELD?

### PR DESCRIPTION
**Pull request by cing**
Fixes #46

This PR essentially just adds new parameters to `SystemBuilder` to interface with already existing tleap functionality in AmberTools/ambermini. I didn't implement the proposed enhancement where a restraining potential should be used to collapse long chains before solvating to reduce box sizes. More discussion needs to be had about the best way to do that. Lots of hardcoded values for the system sizes in the new tests of explicit water boxes. The current water box and ion replacement protocol seems deterministic, but this could be a possible breaking point if tleap algorithms changes in the future.

I'm planning to use this code for the subsequent REST2/AMAP scaling tests so we don't have to distribute as many mdcrd/top files in the test directories of the repo.

### CODE REVIEW

**Comment by cing** [comment]
it's slightly cheating because the `functional` test directory does not seem to run by default, but rest assured all tests in there do pass!

**Comment by jlmaccal** [comment]
>it's slightly cheating because the functional test directory does not seem to run by default, but rest assured all tests in there do pass!

If those don't require a GPU, we should make sure that Travis runs these.

**Comment by jlmaccal** [comment]
This looks good. A couple of thoughts...
- Can we change `solvent_distance` to be in nm?
- Can we specify that the system should be neutralized?
- Can we specify a salt concentration rather than number?

**Comment by cing** [comment]
Great suggestions. I confirmed and Travis does indeed run these functional tests, so my mistake. We could get travis to run `python -m unittest discover -v meld.test` to get some verbose test output.

- Easy unit change, we'll have to flag this argument for eventual units update in #17 

- I agree this would be useful. In tleap, ioncount of "0" will neutralize the solute but it has to be the correct counterion to your net solute charge the subsequent addion call must be suppressed. I'm just wondering how I should calculate solute net charge when the topology hasn't been built yet. I could do a two step tleap process, or perhaps I just use a dictionary of the standard twenty AA -> charge with the molecules string but that would be less general. 

- Again, useful. It's just unclear how many ions to be added to get the desired ionic concentration until we know the box size or water molecules added from the `solvatebox`. Another reason to maybe run tleap in two steps?

**Comment by cing** [comment]
I could also interact with the tleap subprocess to get the output of the commands `charge solute` and `solvatebox` to make the proposed convenience methods, but that's pretty messy/brittle. Any other ideas?

**Pull request merged**
