### PR TITLE
Merge density map restraints feature

### PR DESCRIPTION
**Pull request by ccccclw**
Hi Justin,
 
I merged the density with master branch and resolved the conflict. Here is the output for `make test`:
```
    Start 1: TestSerializeMeldForce
1/4 Test #1: TestSerializeMeldForce ...........   Passed    0.02 sec
    Start 2: TestReferenceMeldForce
2/4 Test #2: TestReferenceMeldForce ...........   Passed    0.02 sec
    Start 3: TestCudaMeldForceSingle
3/4 Test #3: TestCudaMeldForceSingle ..........   Passed   19.28 sec
    Start 4: TestCudaMeldForceMixed
4/4 Test #4: TestCudaMeldForceMixed ...........   Passed   15.57 sec
 
100% tests passed, 0 tests failed out of 4
 
Total Test time (real) =  34.93 sec
```
Here is an error when I tried to run simulation, which I think is related to the implementation of RDC restraints:
```
  File "~/python3.8/site-packages/Meld-0.6.1-py3.8.egg/meld/runner/transform/restraints/meld/meld.py", line 83, in add_intera
tions                                                                                                                        
    meld_force = MeldForce(n_alignments, rdc_scale_factor)
TypeError: __init__() takes 1 positional argument but 3 were given
```

### CODE REVIEW

**Comment by jlmaccal** [comment]
Can you run the python tests as well?

```
python -m unittest discover meld.test
mypy meld
```

I know there were parts of the code that we both changed, so we might need to manually sort things out.

**Comment by ccccclw** [comment]
python test looks passed:
```
.WARNING: No velocities found, setting to zero
............WARNING: No velocities found, setting to zero
.WARNING: No velocities found, setting to zero
.................................................................................................................
----------------------------------------------------------------------
Ran 453 tests in 57.470s

OK (skipped=8)
```
mypy meld gives a minor error for checking module import in density:
```
meld/system/density.py:5: error: Skipping analyzing "scipy.ndimage": module is installed, but missing library stubs or py.typed marker  [import]
meld/system/density.py:5: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
meld/system/density.py:5: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by jlmaccal** [comment]
I think you need to rebuild and re-install the meld plugin. That call now requires those extra parameters, but it seems like your environment still has the old versions around. This is the python wrappers around the C++/CUDA code.

**Comment by ccccclw** [comment]
Indeed, replacing the old version of meldplugin in the env fixed it.

**Comment by jlmaccal** [comment]
Perfect! Looks good. I'll go ahead and merge.

**Comment by ccccclw** [comment]
Thanks!

**Pull request merged**
